export { default as Home } from './Home'
export { default as Login } from './Login'
export { default as SignUp } from './SignUp'
export { default as Profile } from './Profile'
export { default as Events } from './Events'
